FROM kenpu/base:latest

RUN pip install torch torchvision torchaudio torchtext torchmetrics
RUN pip install lightning
RUN pip install -q -U bitsandbytes
RUN pip install -q -U git+https://github.com/huggingface/transformers.git
RUN pip install -q -U git+https://github.com/huggingface/peft.git
RUN pip install -q -U git+https://github.com/huggingface/accelerate.git
